"""add ondelete cascade on actors_and_theatres

Revision ID: a5d48605cdff
Revises: 0465e6134ae9
Create Date: 2025-11-25 15:01:13.643353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d48605cdff'
down_revision: Union[str, Sequence[str], None] = '0465e6134ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('actors_and_theatres_theatre_id_fkey'), 'actors_and_theatres', type_='foreignkey')
    op.drop_constraint(op.f('actors_and_theatres_actor_id_fkey'), 'actors_and_theatres', type_='foreignkey')
    op.create_foreign_key(None, 'actors_and_theatres', 'actors', ['actor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'actors_and_theatres', 'theatres', ['theatre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors_and_theatres', type_='foreignkey')
    op.drop_constraint(None, 'actors_and_theatres', type_='foreignkey')
    op.create_foreign_key(op.f('actors_and_theatres_actor_id_fkey'), 'actors_and_theatres', 'actors', ['actor_id'], ['id'])
    op.create_foreign_key(op.f('actors_and_theatres_theatre_id_fkey'), 'actors_and_theatres', 'theatres', ['theatre_id'], ['id'])
    # ### end Alembic commands ###
